---
# Fixa GRUB como bootloader do sistema instalado (BIOS e UEFI).
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
timeout: "5"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/etc/default/grub"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true

