name: Build NexiliumOS ISO

on:
   workflow_dispatch:
   push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install live-build depedencies
        run: |
          sudo apt update
          sudo apt install -y live-build debootstrap squashfs-tools xorriso \
            isolinux syslinux-common syslinux-utils

      - name: Ensure hooks ae executable
        run: chmod +x nexiliumos/config/hooks/normal/*.hook.chroot

      - name: Configure live-build
        run: |
          cd nexiliumos
          lb config --mode debian --distribution trixie --architecture amd64 --mirror-bootstrap http://deb.debian.org/debian --mirror-chroot http://deb.debian.org/debian --mirror-binary http://deb.debian.org/debian --security false

      - name: Build ISO
        run: |
          cd nexiliumos
          sudo lb build

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: nexiliumos-iso
          path: nexiliumos/*.iso
