name: Build NexiliumOS ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-pc-bin \
            grub-efi-amd64-bin \
            grub-common \
            mtools \
            dosfstools \
            jq \
            curl

      - name: Build NexiliumOS
        run: sudo bash scripts/build.sh

      - name: Upload Gofile
        run: |
          RESPONSE=$(curl -s -F "file=@output/lakeOS.iso" "https://upload.gofile.io/uploadfile?folderId=j3q")
          echo "Response: $RESPONSE"
          LINK=$(echo "$RESPONSE" | jq -r '.data.downloadPage')
          echo "Link: $LINK"
          echo "# NexiliumOS Build #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Download:** $LINK" >> $GITHUB_STEP_SUMMARY
